import Amazon from "@/icons/logos/amazon"
import Amex from "@/icons/amex"
import Apple from "@/icons/logos/apple"
import AppointmentReminders from "@/icons/appointment-reminders"
import Binoculars from "@/icons/binoculars"
import BookmarkRibon from "@/icons/bookmark-ribbon"
import Box from "@/icons/box"
import Briefcase from "@/icons/briefcase"
import Cash from "@/icons/cash"
import Checked from "@/icons/checked"
import Checkmark from "@/icons/checkmark"
import Clock from "@/icons/clock"
import Dlelte from "@/icons/delete"
import DeleteSign from "@/icons/delete-sighn"
import Document from "@/icons/document"
import Dropbox from "@/icons/logos/dropbox"
import Edit from "@/icons/edit"
import Ethereum from "@/icons/logos/ethereum"
import Fastag from "@/icons/fastag"
import File from "@/icons/file"
import FolderInvoices from "@/icons/folder-invoices"
import Google from "@/icons/google"
import Home from "@/icons/home"
import Idea from "@/icons/idea"
import ImageFile from "@/icons/image-file"
import Info from "@/icons/info"
import Menu from "@/icons/menu"
import Percentage from "@/icons/percentage"
import Tinder from "@/icons/tinder"
import Bitcoin from "@/icons/logos/bitcoin"
import React from "react"
import Instacart from "@/icons/instacart"
import MacOS from "@/icons/mac-os"
import MailboxClosedFlagDown from "@/icons/mailbox-closed-flag-down"
import Mastercard from "@/icons/mastercard"
import Music from "@/icons/music"
import Myspace from "@/icons/myspace"
import News from "@/icons/news"
import Ok from "@/icons/ok"
import OpenedFolder from "@/icons/opened-folder"
import Paypal from "@/icons/paypal"
import Pinterest from "@/icons/pinterest"
import Reddit from "@/icons/reddit"
import Restart from "@/icons/restart"
import RubyProgrammingLanguage from "@/icons/ruby-programming-language"
import Settings from "@/icons/settings"
import Snapchat from "@/icons/snapchat"
import SpeechBubble from "@/icons/speech-bubble"
import Stumbleupon from "@/icons/stumbleupon"
import Sun from "@/icons/sun"
import Support from "@/icons/support"
import Swift from "@/icons/swift"
import Toolbox from "@/icons/toolbox"
import Trash from "@/icons/trash"
import Twitter from "@/icons/twitter"
import UserFemale from "@/icons/user-female"
import UserMale from "@/icons/user-male"
import Visa from "@/icons/visa"
import Windows8 from "@/icons/windows8"

export default function Page() {
  return (
    <div className='flex gap-5 p-16 flex-wrap'>
      <Apple width='4em' height='4em' />
      <Bitcoin width='4em' height='4em' />
      <Amazon width='4em' height='4em' />
      <Amex width='4em' height='4em' />
      <AppointmentReminders width='4em' height='4em' />
      <Binoculars width='4em' height='4em' />
      <BookmarkRibon width='4em' height='4em' />
      <Box width='4em' height='4em' />
      <Briefcase width='4em' height='4em' />
      <Cash width='4em' height='4em' />
      <Checked width='4em' height='4em' />
      <Checkmark width='4em' height='4em' />
      <Clock width='4em' height='4em' />
      <DeleteSign width='4em' height='4em' />
      <Dlelte width='4em' height='4em' />
      <Document width='4em' height='4em' />
      <Dropbox width='4em' height='4em' />
      <Edit width='4em' height='4em' />
      <Ethereum width='4em' height='4em' />
      <Fastag width='4em' height='4em' />
      <File width='4em' height='4em' />
      <FolderInvoices width='4em' height='4em' />
      <Google width='4em' height='4em' />
      <Home width='4em' height='4em' />
      <Idea width='4em' height='4em' />
      <ImageFile width='4em' height='4em' />
      <Info width='4em' height='4em' />
      <Menu width='4em' height='4em' />
      <Percentage width='4em' height='4em' />
      <Tinder width='4em' height='4em' />
      <Instacart width='4em' height='4em' />
      <MacOS width='4em' height='4em' />
      <MailboxClosedFlagDown width='4em' height='4em' />
      <Mastercard width='4em' height='4em' />
      <Music width='4em' height='4em' />
      <Myspace width='4em' height='4em' />
      <News width='4em' height='4em' />
      <Ok width='4em' height='4em' />
      <OpenedFolder width='4em' height='4em' />
      <Paypal width='4em' height='4em' />
      <Pinterest width='4em' height='4em' />
      <Reddit width='4em' height='4em' />
      <Restart width='4em' height='4em' />
      <RubyProgrammingLanguage width='4em' height='4em' />
      <Settings width='4em' height='4em' />
      <Snapchat width='4em' height='4em' />
      <SpeechBubble width='4em' height='4em' />
      <Stumbleupon width='4em' height='4em' />
      <Sun width='4em' height='4em' />
      <Support width='4em' height='4em' />
      <Swift width='4em' height='4em' />
      <Toolbox width='4em' height='4em' />
      <Trash width='4em' height='4em' />
      <Twitter width='4em' height='4em' />
      <UserFemale width='4em' height='4em' />
      <UserMale width='4em' height='4em' />
      <Visa width='4em' height='4em' />
      <Windows8 width='4em' hanging='4em' />
    </div>
  )
}
